[phases.setup]
nixPkgs = ["nodejs", "python3", "gcc"]

[phases.install]
cmds = ["npm install --prefix backend", "npm install --prefix frontend"]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "npm start"
